#!/bin/sh
# [O]pen [F]ile using custom programs
#
# TODO: sxiv for images

filename=$1

[ -z "$filename" ] \
  && filename=$(fd -E '{aur,texmf}' -t f . $HOME \
  | sed -e "s|^$HOME|~|" \
  | fzf \
  | sed -e "s|^~|$HOME|")

[ -z $filename ] && exit 1

case "$filename" in
	*.pdf) setsid -f "$READER" "$filename" >/dev/null 2>&1 & ;;
  *.png|*.jpg|*.jpeg|*.gif) setsid -f sxiv "$filename" >/dev/null 2>&1 & ;;
	*.html|*.htm) setsid -f "$BROWSER" "$filename" >/dev/null 2>&1 & ;;
	*.sent) setsid -f sent "$filename" >/dev/null 2>&1 & ;;
  *) setsid -f xdg-open "$filename" >/dev/null 2>&1 & ;;
esac
